spring.application.name=BFF-GATEWAY
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

smartlogix.inventario.url=http://MS-INVENTARIO
smartlogix.pedidos.url=http://MS-PEDIDOS
smartlogix.envios.url=http://MS-ENVIOS

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
