spring.application.name=MS-PEDIDOS
server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.datasource.url=jdbc:postgresql://localhost:5432/pedidos_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

smartlogix.inventario.base-url=http://MS-INVENTARIO

resilience4j.circuitbreaker.instances.inventario.slidingWindowSize=10
resilience4j.circuitbreaker.instances.inventario.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventario.waitDurationInOpenState=10s
